!classDefinition: #Pepe category: #'Segunda Actividad'!
DenotativeObject subclass: #Pepe
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Segunda Actividad'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'Pepe class' category: #'Segunda Actividad'!
Pepe class
	instanceVariableNames: ''!

!Pepe class methodsFor: 'as yet unclassified' stamp: 'JEC 3/19/2018 20:16:04'!
hola

	^'chau'! !
